### ISSUE TITLE
Add hints under password field and relevants validations

### ISSUE THREAD

**Issue by Trane-24** [Trane-24/first_project#15]
Add hints under password field and relevants validations on sign up form and profile page

* Your password must be 8 or more characters in length.
* Your password must contain 1 or more uppercase and lowercase characters.
* Your password must contain 1 or more special characters.

intersects with #12 ticket

**Comment by Oleh-Khashchevskyi** [comment]
![Screenshot 2022-08-30 at 16 46 25](https://user-images.githubusercontent.com/92041347/187453884-21f9c899-f91e-49a3-9723-d0b4c47f3545.png)
![Screenshot 2022-08-30 at 16 46 47](https://user-images.githubusercontent.com/92041347/187453888-d6fa2537-2c0a-4dd4-90a0-8aa1a507533a.png)

@Pavlo-Khashchevskyi, should add validation to the new password when the confirmation password is entered
and vice versa

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi, you need to add the ability to view the entered password
also after submit form, the fields with the password should be reset

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi reproduced

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi reproduced

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi 
![Screenshot 2022-09-09 at 14 37 55](https://user-images.githubusercontent.com/92041347/189341719-c1822bf4-765c-431a-b798-b6f35d9f05d7.png)
