### ISSUE TITLE
User lists

### ISSUE THREAD

**Issue by Trane-24** [Trane-24/first_project#3]
Create a owner\guest list pages
You may get all users and filtered their by role
Add title - "Owners" or "Guests" and creation button
should have all CRUD capabilities

User schema
email* | string
firstName* | string
lastName* | string
phone | string
role* | string

**Comment by Trane-24** [comment]
@Pavlo-Khashchevskyi will be added beew API
I will provide the endpoints later

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi BE Done
GET /api/users - List users
GET /api/users/:id - Get user by id
POST /api/users - Create user
PUT /api/users/:id - Update user
DELETE /api/users/:id - Delete user

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi 
You need to add pagination to Users list

Updated response, now you get object with fields: data and total

so UI will be broken until fixed
