### ISSUE TITLE
Hotel list

### ISSUE THREAD

**Issue by Trane-24** [Trane-24/first_project#4]
Create a hotels list page
Add title and creation button
should have all CRUD capabilities

Hotel schema
name* | string
country | string
city | string
imgUrl | string
description | string
ownerId* | number

add MUI autocomplete to form for owners

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi BE Done
GET /api/hotels - List hotels
GET /api/hotels/:id - Get hotel by id
POST /api/hotels - Create hotel
PUT /api/hotels/:id - Update hotel
DELETE /api/hotels/:id - Delete hotel

return DTO:
name | string
country | string
city | string
owner | User

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi BE Done
GET /api/hotels - List hotels
GET /api/hotels/:id - Get hotel by id
POST /api/hotels - Create hotel
PUT /api/hotels/:id - Update hotel
DELETE /api/hotels/:id - Delete hotel

return DTO:
_id | string
name | string
country | string
city | string
imgUrl | string
description | string
owner | User

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi BE Done
Check Response and DTO

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi  Updated hotels response, now you get object with fields: data and total
add pagination to hotels list

**Comment by Trane-24** [comment]
![Screenshot 2022-08-17 at 20 08 01](https://user-images.githubusercontent.com/110428839/185202036-56e63242-4aae-47c0-81b5-821ea0b20a44.png)

1. let's remove the top and bottom margins
2. let's not change the font size and bold on opening card and keep the font smaller and bold. I still can't select the text either
3. this image is not informative. let's add some text eg "no available" or "image no available"
4. the title of the description must be moved to the description itself
5. menu options should be aligned

**Comment by Trane-24** [comment]
@Pavlo-Khashchevskyi Also change lists and items style, just like on the users list

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi styles are not the same as listed by users
