### ISSUE TITLE
Reservations list

### ISSUE THREAD

**Issue by Trane-24** [Trane-24/first_project#7]
Create a reservations list page
Add title and creation button
should have all CRUD capabilities

Reservation schema
startDate* | string (format YYYY-MM-DD)
endDate* | string (format YYYY-MM-DD)
notes | string
guestId* | string
hotelId* | string

for work with dates use dayjs library

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi BE Done
GET /api/reservations - List reservations
GET /api/reservations/:id - Get reservations by id
POST /api/reservations - Create reservation
PUT /api/reservations/:id - Update reservation
DELETE /api/reservations/:id - Delete reservation

return DTO:
_id | string
startDate | string
endDate | string
notes | string
guest | User
hotel | Hotel

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi BE Done

**Comment by Oleh-Khashchevskyi** [comment]
after creating a reservation, the new reservation should be displayed at the top

need to add validation on dates
![Screenshot 2022-08-26 at 09 29 57](https://user-images.githubusercontent.com/92041347/186837182-12a300aa-e811-44d8-946c-1264b606b759.png)

notes should be optional
![Screenshot 2022-08-26 at 09 31 12](https://user-images.githubusercontent.com/92041347/186837396-e82b2769-3581-4739-b9c7-8a64d6753c6a.png)

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi also add pagination if list is not empty

**Comment by Oleh-Khashchevskyi** [comment]
@Pavlo-Khashchevskyi,
I suggest move notes to the bottom and showing them only if the map is expanded
Show the hotel name first, in bold. Similar to how it is done in the hotels list
Information about the owner should also be shown

Dates should be displayed in one column
Like here:

01 Aug 2022
Aug 1 - 8, 2022
Jul 25 - Aug 1, 2022
Jul 25, 2022 - Aug 1, 2023

**Comment by Oleh-Khashchevskyi** [comment]
![Screenshot 2022-09-05 at 19 03 17](https://user-images.githubusercontent.com/92041347/188486410-17eca672-86f0-45c1-813b-93a1200335e6.png)

Should be Sep 05, 2022 - Feb 02, 2023
